/*
 * Ibis
 *
 * API for Ibis
 *
 * API version: 1.0.0
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

import (
	"context"
	"net/http"
)

// GameApiRouter defines the required methods for binding the api requests to a responses for the GameApi
// The GameApiRouter implementation should parse necessary information from the http request,
// pass the data to a GameApiServicer to perform the required actions, then write the service results to the http response.
type GameApiRouter interface {
	ListGames(http.ResponseWriter, *http.Request)
	ListUserGameInstances(http.ResponseWriter, *http.Request)
}

// UserApiRouter defines the required methods for binding the api requests to a responses for the UserApi
// The UserApiRouter implementation should parse necessary information from the http request,
// pass the data to a UserApiServicer to perform the required actions, then write the service results to the http response.
type UserApiRouter interface {
	GetUserByName(http.ResponseWriter, *http.Request)
	ListUserFriends(http.ResponseWriter, *http.Request)
	ListUsers(http.ResponseWriter, *http.Request)
}

// GameApiServicer defines the api actions for the GameApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type GameApiServicer interface {
	ListGames(context.Context) (ImplResponse, error)
	ListUserGameInstances(context.Context, string) (ImplResponse, error)
}

// UserApiServicer defines the api actions for the UserApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type UserApiServicer interface {
	GetUserByName(context.Context, string) (ImplResponse, error)
	ListUserFriends(context.Context, string) (ImplResponse, error)
	ListUsers(context.Context) (ImplResponse, error)
}
