/*
 * Ibis
 *
 * API for Ibis
 *
 * API version: 1.0.0
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// GameApiController binds http requests to an api service and writes the service results to the http response
type GameApiController struct {
	service      GameApiServicer
	errorHandler ErrorHandler
}

// GameApiOption for how the controller is set up.
type GameApiOption func(*GameApiController)

// WithGameApiErrorHandler inject ErrorHandler into controller
func WithGameApiErrorHandler(h ErrorHandler) GameApiOption {
	return func(c *GameApiController) {
		c.errorHandler = h
	}
}

// NewGameApiController creates a default api controller
func NewGameApiController(s GameApiServicer, opts ...GameApiOption) Router {
	controller := &GameApiController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all of the api route for the GameApiController
func (c *GameApiController) Routes() Routes {
	return Routes{
		{
			"ListGames",
			strings.ToUpper("Get"),
			"/game",
			c.ListGames,
		},
		{
			"ListUserGameInstances",
			strings.ToUpper("Get"),
			"/user/{username}/instances",
			c.ListUserGameInstances,
		},
	}
}

// ListGames - lists games in system
func (c *GameApiController) ListGames(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.ListGames(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}

// ListUserGameInstances - lists user games in system
func (c *GameApiController) ListUserGameInstances(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	usernameParam := params["username"]

	result, err := c.service.ListUserGameInstances(r.Context(), usernameParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)

}
