/*
 * Ibis
 *
 * API for Ibis
 *
 * API version: 1.0.0
 * Contact: holmes89@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
