/**
 * Ibis
 * API for Ibis
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: holmes89@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GameInstance model module.
 * @module model/GameInstance
 * @version 1.0.0
 */
class GameInstance {
    /**
     * Constructs a new <code>GameInstance</code>.
     * @alias module:model/GameInstance
     */
    constructor() { 
        
        GameInstance.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameInstance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameInstance} obj Optional instance to populate.
     * @return {module:model/GameInstance} The populated <code>GameInstance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameInstance();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('game')) {
                obj['game'] = ApiClient.convertToType(data['game'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Date');
            }
            if (data.hasOwnProperty('total_time_seconds')) {
                obj['total_time_seconds'] = ApiClient.convertToType(data['total_time_seconds'], 'Number');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], File);
            }
            if (data.hasOwnProperty('autosave')) {
                obj['autosave'] = ApiClient.convertToType(data['autosave'], File);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
GameInstance.prototype['id'] = undefined;

/**
 * @member {String} game
 */
GameInstance.prototype['game'] = undefined;

/**
 * @member {String} user
 */
GameInstance.prototype['user'] = undefined;

/**
 * @member {Date} start_time
 */
GameInstance.prototype['start_time'] = undefined;

/**
 * @member {Number} total_time_seconds
 */
GameInstance.prototype['total_time_seconds'] = undefined;

/**
 * @member {String} parent_id
 */
GameInstance.prototype['parent_id'] = undefined;

/**
 * @member {File} state
 */
GameInstance.prototype['state'] = undefined;

/**
 * @member {File} autosave
 */
GameInstance.prototype['autosave'] = undefined;






export default GameInstance;

